import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      // Generated by Next.js (triple-slash references); not ours to lint.
      "apps/web/next-env.d.ts",
      "coverage/**",
      // Legacy standalone artifacts (pre-monorepo); superseded by apps/ + packages/.
      "extension/**",
      "figma-plugin/**",
      // Vendored capture/builder engines moved verbatim in Phase 0 (// @ts-nocheck, not linted).
      "packages/capture-core/src/content.js",
      "packages/figma-builder/src/code.js",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Node-side TypeScript (relay, worker, mcp, client, schema) + build/test scripts.
    files: ["**/*.{ts,mts,cts}", "**/*.{js,mjs,cjs}"],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      "no-console": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // Browser-context capture code runs in the page (DOM globals).
    files: ["packages/capture-core/**/*.ts", "apps/extension/**/*.{js,ts}"],
    languageOptions: {
      globals: { ...globals.browser },
    },
  },
  {
    // Extension + plugin glue: browser/runtime globals (chrome, figma) are ambient and message
    // payloads are dynamically typed. TS (tsc) does the real undefined/any checking here.
    files: ["apps/extension/src/**/*.ts", "apps/figma-plugin/src/**/*.ts"],
    languageOptions: {
      globals: { ...globals.browser, chrome: "readonly", figma: "readonly", __html__: "readonly" },
    },
    rules: {
      "no-undef": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  {
    // Next.js web app: server components run in Node, client components in the browser. JSX type
    // references (React.ReactNode etc.) are checked by tsc, so no-undef is off here (mirrors the
    // extension/plugin glue). Keep the ^_ unused-var convention for .tsx too.
    files: ["apps/web/**/*.{ts,tsx}"],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      "no-undef": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // CommonJS test harnesses: node + jsdom-style page globals; require() is intentional.
    files: ["test/**/*.js"],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
);
